"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import th2_grpc_lw_data_provider.lw_data_provider_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class MessageGroupsQueueSearchRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    START_TIMESTAMP_FIELD_NUMBER: builtins.int
    END_TIMESTAMP_FIELD_NUMBER: builtins.int
    MESSAGE_GROUP_FIELD_NUMBER: builtins.int
    SYNC_INTERVAL_FIELD_NUMBER: builtins.int
    EXTERNAL_QUEUE_FIELD_NUMBER: builtins.int
    KEEP_ALIVE_FIELD_NUMBER: builtins.int
    @property
    def start_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def message_group(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[th2_grpc_lw_data_provider.lw_data_provider_pb2.MessageGroupsSearchRequest.Group]: ...
    @property
    def sync_interval(self) -> google.protobuf.duration_pb2.Duration: ...
    external_queue: typing.Text
    keep_alive: builtins.bool
    def __init__(self,
        *,
        start_timestamp: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        end_timestamp: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        message_group: typing.Optional[typing.Iterable[th2_grpc_lw_data_provider.lw_data_provider_pb2.MessageGroupsSearchRequest.Group]] = ...,
        sync_interval: typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        external_queue: typing.Text = ...,
        keep_alive: builtins.bool = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["end_timestamp",b"end_timestamp","start_timestamp",b"start_timestamp","sync_interval",b"sync_interval"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["end_timestamp",b"end_timestamp","external_queue",b"external_queue","keep_alive",b"keep_alive","message_group",b"message_group","start_timestamp",b"start_timestamp","sync_interval",b"sync_interval"]) -> None: ...
global___MessageGroupsQueueSearchRequest = MessageGroupsQueueSearchRequest

class MessageLoadedStatistic(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class GroupStat(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        GROUP_FIELD_NUMBER: builtins.int
        COUNT_FIELD_NUMBER: builtins.int
        @property
        def group(self) -> th2_grpc_lw_data_provider.lw_data_provider_pb2.MessageGroupsSearchRequest.Group: ...
        count: builtins.int
        def __init__(self,
            *,
            group: typing.Optional[th2_grpc_lw_data_provider.lw_data_provider_pb2.MessageGroupsSearchRequest.Group] = ...,
            count: builtins.int = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["group",b"group"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["count",b"count","group",b"group"]) -> None: ...

    STAT_FIELD_NUMBER: builtins.int
    @property
    def stat(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MessageLoadedStatistic.GroupStat]: ...
    def __init__(self,
        *,
        stat: typing.Optional[typing.Iterable[global___MessageLoadedStatistic.GroupStat]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["stat",b"stat"]) -> None: ...
global___MessageLoadedStatistic = MessageLoadedStatistic
