# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: th2_grpc_lw_data_provider/queue_data_provider.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from th2_grpc_lw_data_provider import lw_data_provider_pb2 as th2__grpc__lw__data__provider_dot_lw__data__provider__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3th2_grpc_lw_data_provider/queue_data_provider.proto\x12\x14th2.data_provider.lw\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x30th2_grpc_lw_data_provider/lw_data_provider.proto\"\xb6\x02\n\x1fMessageGroupsQueueSearchRequest\x12\x33\n\x0fstart_timestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rend_timestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12M\n\rmessage_group\x18\x03 \x03(\x0b\x32\x36.th2.data_provider.lw.MessageGroupsSearchRequest.Group\x12\x30\n\rsync_interval\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x16\n\x0e\x65xternal_queue\x18\x05 \x01(\t\x12\x12\n\nkeep_alive\x18\x06 \x01(\x08\"\xc1\x01\n\x16MessageLoadedStatistic\x12\x44\n\x04stat\x18\x01 \x03(\x0b\x32\x36.th2.data_provider.lw.MessageLoadedStatistic.GroupStat\x1a\x61\n\tGroupStat\x12\x45\n\x05group\x18\x01 \x01(\x0b\x32\x36.th2.data_provider.lw.MessageGroupsSearchRequest.Group\x12\r\n\x05\x63ount\x18\x02 \x01(\x04\x32\x8f\x01\n\x11QueueDataProvider\x12z\n\x13SearchMessageGroups\x12\x35.th2.data_provider.lw.MessageGroupsQueueSearchRequest\x1a,.th2.data_provider.lw.MessageLoadedStatisticB)\n%com.exactpro.th2.dataprovider.lw.grpcP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'th2_grpc_lw_data_provider.queue_data_provider_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.exactpro.th2.dataprovider.lw.grpcP\001'
  _MESSAGEGROUPSQUEUESEARCHREQUEST._serialized_start=193
  _MESSAGEGROUPSQUEUESEARCHREQUEST._serialized_end=503
  _MESSAGELOADEDSTATISTIC._serialized_start=506
  _MESSAGELOADEDSTATISTIC._serialized_end=699
  _MESSAGELOADEDSTATISTIC_GROUPSTAT._serialized_start=602
  _MESSAGELOADEDSTATISTIC_GROUPSTAT._serialized_end=699
  _QUEUEDATAPROVIDER._serialized_start=702
  _QUEUEDATAPROVIDER._serialized_end=845
# @@protoc_insertion_point(module_scope)
