
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-09T18:40:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f8e4bf05723b51a0d1f5e7041dcc4b82e218a5d",
 "version": "1.18.2.post0.dev31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
