
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-08T07:52:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "80b87be7ee5c84230adea5f15e13e94aee1fc9c2",
 "version": "1.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
