# Generated by Django 2.2.15 on 2020-09-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psu_base", "0016_error_debug_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="error",
            name="browser",
            field=models.CharField(
                blank=True, help_text="Browser info", max_length=200, null=True
            ),
        ),
    ]
