
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-08T06:34:32-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "971cd0ae1aa02977dc106ebadbffd1273eec6ee9",
 "version": "4.9.62"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
