# Generated by Django 2.2.4 on 2020-03-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psu_base", "0010_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Xss",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_code",
                    models.CharField(
                        help_text="Application that this attempt was made in.",
                        max_length=15,
                        verbose_name="Application Code",
                    ),
                ),
                ("path", models.CharField(help_text="Request path", max_length=200)),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Authenticated username",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "parameter_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Parameter name",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "parameter_value",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Parameter content",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "review_username",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Reviewed by",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
