VERSION_YEAR = 2023
VERSION_MONTH = int('02')
VERSION_DAY = int('09')
VERSION_HOUR = int('12')
VERSION_MINUTE = int('37')
MAJOR_VERSION = 0
MINOR_VERSION = 26
PATCH_VERSION = 202302091237
version_date = '2023/02/09 12:37'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
