# Generated by Django 3.2 on 2023-02-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugdirectory',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='drugdirectory',
            name='price',
        ),
        migrations.AddField(
            model_name='drugdirectory',
            name='gb_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='国家贯标编码'),
        ),
        migrations.AddField(
            model_name='drugdirectory',
            name='gb_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='国家贯标名称'),
        ),
        migrations.AddField(
            model_name='drugdirectory',
            name='hr_level',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='高危等级'),
        ),
        migrations.AddField(
            model_name='drugdirectory',
            name='is_essential',
            field=models.BooleanField(default=True, verbose_name='是否是基药'),
        ),
        migrations.AddField(
            model_name='drugdirectory',
            name='measure_unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='计量单位'),
        ),
        migrations.AddField(
            model_name='drugdirectory',
            name='mic',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='医保类别'),
        ),
        migrations.AddField(
            model_name='drugdirectory',
            name='rcc_category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='农合类别'),
        ),
        migrations.AddField(
            model_name='drugdirectory',
            name='stock_left',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='库存数量'),
        ),
        migrations.AddField(
            model_name='drugdirectory',
            name='stock_unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='库存单位'),
        ),
        migrations.AddField(
            model_name='drugdirectory',
            name='unit_dose',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='单位剂量'),
        ),
    ]
