class DatabricksApiType:
    secret: str = 'secret'
    workspace: str = 'workspace'
    job: str = 'job'
    cluster: str = 'cluster'
    pool: str = 'pool'
    library: str = 'library'
    token: str = 'token'
    sql_endpoint: str = 'sql_endpoint'
    databricks_file_system: str = 'databricks_file_system'
