
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-10T10:39:27+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "02a511bdb0acedbd19fa182c79c174aac2ca0fb1",
 "version": "2.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
