# Generated by Django 2.2.15 on 2020-11-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psu_base", "0017_error_browser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="This holds the username of the event performer, which could be a provisional email address",
                max_length=128,
                null=True,
            ),
        ),
    ]
