from enum import Enum

class UserBankCodes(Enum):
  CL_FALABELLA = 'CL_FALABELLA'
  CL_ESTADO = 'CL_ESTADO'
  CL_SCOTIABANK = 'CL_SCOTIABANK'
  CL_SANTANDER = 'CL_SANTANDER'
  CL_ITAU = 'CL_ITAU'
  CL_BCH = 'CL_BCH'
  CL_BCI = 'CL_BCI'
  CL_TEST = 'CL_TEST'
  
  MX_BBVA = 'MX_BBVA'
  MX_BANAMEX = 'MX_BANAMEX'
  MX_SCOTIABANK = 'MX_SCOTIABANK'
  MX_SANTANDER = 'MX_SANTANDER'
  MX_BANORTE = 'MX_BANORTE'
  MX_AZTECA = 'MX_AZTECA'
  MX_BANREGIO = 'MX_BANREGIO'
  MX_TEST = 'MX_TEST'