# Generated by Django 3.2.11 on 2022-02-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu_base', '0025_student_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='student',
            name='name_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
