VERSION_YEAR = 2023
VERSION_MONTH = int('02')
VERSION_DAY = int('08')
VERSION_HOUR = int('13')
VERSION_MINUTE = int('20')
MAJOR_VERSION = 0
MINOR_VERSION = 25
PATCH_VERSION = 202302081320
version_date = '2023/02/08 13:20'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
