def get_external_id_bytes(b: bytes, prefix: str) -> str: ...
def get_external_id_str(name: str, prefix: str) -> str: ...
def get_db_eid(database_name: str) -> str: ...
def get_table_eid(table_name: str) -> str: ...
def get_job_eid(job_name: str) -> str: ...
def get_req_eid() -> str: ...
def get_external_id_bytes_blake3(b: bytes, prefix: str) -> str: ...
def get_external_id_str_blake3(name: str, prefix: str) -> str: ...
def get_org_eid(email_domian: str) -> str: ...
def get_user_eid(email_address: str) -> str: ...
def get_eval_eid() -> str: ...
def get_mat_eid() -> str: ...
def get_mat_group_eid() -> str: ...
