
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-09T15:52:00-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9eea81fe56fdf5e78debcc0c8ef1e7e0ede58d84",
 "version": "2.6.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
