
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-09T15:56:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e3ae536bf6368131002f4b53bcd0e8fdec653bd7",
 "version": "2023.02.09"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
