# Generated by Django 4.0.4 on 2022-07-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obpages", "0003_usersequence_create_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersequence",
            name="curated",
            field=models.BooleanField(
                default=False, help_text="Whether the sequence has been curated."
            ),
        ),
    ]
