
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-06T17:19:44-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4879a2f5ef2cca8cf628db752be681cfad721a7a",
 "version": "0.2.63.post0.dev77"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
