# coding: utf-8

# flake8: noqa

"""
IGNORE:
    Nutanix Vmm Versioned APIs

    Manage the life-cycle of virtual machines hosted on Nutanix  # noqa: E501

    OpenAPI spec version: 4.0.2-alpha-1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
IGNORE
"""
from __future__ import absolute_import

# import models into model package
from ntnx_vmm_py_client.Ntnx.OneOfcommon.v1.config.KVPairvalue import KVPairvalue
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.AssignIpResponsedata import AssignIpResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.AttachVmCategoryResponsedata import AttachVmCategoryResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.CloneOverrideboot_config import CloneOverrideboot_config
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.CloneVmResponsedata import CloneVmResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.CloudInitcloud_init_script import CloudInitcloud_init_script
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.CreateCdromResponsedata import CreateCdromResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.CreateDiskResponsedata import CreateDiskResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.CreateGpuResponsedata import CreateGpuResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.CreateNicResponsedata import CreateNicResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.CreateSerialPortResponsedata import CreateSerialPortResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.CreateVmResponsedata import CreateVmResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.CustomizeGuestVmResponsedata import CustomizeGuestVmResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.DataSourcereference import DataSourcereference
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.DeleteCdromResponsedata import DeleteCdromResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.DeleteDiskResponsedata import DeleteDiskResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.DeleteGpuResponsedata import DeleteGpuResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.DeleteNicResponsedata import DeleteNicResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.DeleteSerialPortResponsedata import DeleteSerialPortResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.DeleteVmResponsedata import DeleteVmResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.DetachVmCategoryResponsedata import DetachVmCategoryResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.Diskbacking_info import Diskbacking_info
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.EjectCdromResponsedata import EjectCdromResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.GetCdromResponsedata import GetCdromResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.GetDiskResponsedata import GetDiskResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.GetGpuResponsedata import GetGpuResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.GetGuestToolsResponsedata import GetGuestToolsResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.GetNicResponsedata import GetNicResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.GetSerialPortResponsedata import GetSerialPortResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.GetVmCategoriesResponsedata import GetVmCategoriesResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.GetVmOwnershipInfoResponsedata import GetVmOwnershipInfoResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.GetVmResponsedata import GetVmResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.GuestCustomizationconfig import GuestCustomizationconfig
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.InsertCdromResponsedata import InsertCdromResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.InsertVmGuestToolsResponsedata import InsertVmGuestToolsResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.InstallVmGuestToolsResponsedata import InstallVmGuestToolsResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.LegacyBootboot_device import LegacyBootboot_device
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.ListCdromsResponsedata import ListCdromsResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.ListDisksResponsedata import ListDisksResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.ListGpusResponsedata import ListGpusResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.ListNicsResponsedata import ListNicsResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.ListSerialPortsResponsedata import ListSerialPortsResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.ListVmsResponsedata import ListVmsResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.MigrateNicResponsedata import MigrateNicResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.PowerCycleVmResponsedata import PowerCycleVmResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.PowerOffVmResponsedata import PowerOffVmResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.PowerOnVmResponsedata import PowerOnVmResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.RebootVmResponsedata import RebootVmResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.ReleaseIpResponsedata import ReleaseIpResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.ResetVmResponsedata import ResetVmResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.RevertVmResponsedata import RevertVmResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.ShutdownVmResponsedata import ShutdownVmResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.Sysprepsysprep_script import Sysprepsysprep_script
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.UninstallVmGuestToolsResponsedata import UninstallVmGuestToolsResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.UpdateCdromResponsedata import UpdateCdromResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.UpdateDiskResponsedata import UpdateDiskResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.UpdateGuestToolsResponsedata import UpdateGuestToolsResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.UpdateNicResponsedata import UpdateNicResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.UpdateSerialPortResponsedata import UpdateSerialPortResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.UpdateVmCategoriesResponsedata import UpdateVmCategoriesResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.UpdateVmOwnershipInfoResponsedata import UpdateVmOwnershipInfoResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.UpdateVmResponsedata import UpdateVmResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.UpgradeVmGuestToolsResponsedata import UpgradeVmGuestToolsResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.VmCrossClusterMigrateWithStorageResponsedata import VmCrossClusterMigrateWithStorageResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.ahv.config.Vmboot_config import Vmboot_config
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.config.CloudInitconfig import CloudInitconfig
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.config.Sysprepconfig import Sysprepconfig
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.config.VMTemplateBootDeviceconfig import VMTemplateBootDeviceconfig
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.config.VMTemplateGuestCustomizationconfig import VMTemplateGuestCustomizationconfig
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.error.ErrorResponseerror import ErrorResponseerror
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.images.ImageApiResponsedata import ImageApiResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.images.ImageCategoriesApiResponsedata import ImageCategoriesApiResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.images.ImageClusterLocationListApiResponsedata import ImageClusterLocationListApiResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.images.ImageListApiResponsedata import ImageListApiResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.images.ImagePlacementPolicyListApiResponsedata import ImagePlacementPolicyListApiResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.images.ImagesTaskApiResponsedata import ImagesTaskApiResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.images.Imagesource import Imagesource
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.images.PlacementPolicyApiResponsedata import PlacementPolicyApiResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.images.PlacementPolicyListApiResponsedata import PlacementPolicyListApiResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.images.RateLimitApiResponsedata import RateLimitApiResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.images.RateLimitListApiResponsedata import RateLimitListApiResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.images.RateLimitTaskListApiResponsedata import RateLimitTaskListApiResponsedata
from ntnx_vmm_py_client.Ntnx.OneOfvmm.v4.images.ResolveRateLimitsApiResponsedata import ResolveRateLimitsApiResponsedata
from ntnx_vmm_py_client.Ntnx.common.v1.config.Flag import Flag
from ntnx_vmm_py_client.Ntnx.common.v1.config.IPAddress import IPAddress
from ntnx_vmm_py_client.Ntnx.common.v1.config.IPv4Address import IPv4Address
from ntnx_vmm_py_client.Ntnx.common.v1.config.IPv6Address import IPv6Address
from ntnx_vmm_py_client.Ntnx.common.v1.config.KVPair import KVPair
from ntnx_vmm_py_client.Ntnx.common.v1.config.Message import Message
from ntnx_vmm_py_client.Ntnx.common.v1.config.MessageSeverity import MessageSeverity
from ntnx_vmm_py_client.Ntnx.common.v1.config.TenantAwareModel import TenantAwareModel
from ntnx_vmm_py_client.Ntnx.common.v1.response.ApiLink import ApiLink
from ntnx_vmm_py_client.Ntnx.common.v1.response.ApiResponseMetadata import ApiResponseMetadata
from ntnx_vmm_py_client.Ntnx.common.v1.response.ExternalizableAbstractModel import ExternalizableAbstractModel
from ntnx_vmm_py_client.Ntnx.dataprotection.v4.config.RecoveryPointProperties import RecoveryPointProperties
from ntnx_vmm_py_client.Ntnx.dataprotection.v4.config.RecoveryPointStatus import RecoveryPointStatus
from ntnx_vmm_py_client.Ntnx.dataprotection.v4.config.RecoveryPointType import RecoveryPointType
from ntnx_vmm_py_client.Ntnx.dataprotection.v4.config.VendorSpecificProperty import VendorSpecificProperty
from ntnx_vmm_py_client.Ntnx.prism.v4.config.TaskReference import TaskReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ACPIPowerOptions import ACPIPowerOptions
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ADSFDiskMigrationPlan import ADSFDiskMigrationPlan
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ADSFVmStorageConfig import ADSFVmStorageConfig
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ADSFVolumeGroupReference import ADSFVolumeGroupReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.AssignIp import AssignIp
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.AssignIpResponse import AssignIpResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.AttachVmCategoryResponse import AttachVmCategoryResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.AvailabilityZoneReference import AvailabilityZoneReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.BootDeviceDisk import BootDeviceDisk
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.BootDeviceNic import BootDeviceNic
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.BootDeviceType import BootDeviceType
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CategoryReference import CategoryReference as AhvConfigCategoryReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.Cdrom import Cdrom
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CdromAddress import CdromAddress
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CdromBusType import CdromBusType
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CdromInsert import CdromInsert
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CloneOverride import CloneOverride
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CloneVmResponse import CloneVmResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CloudInit import CloudInit as AhvConfigCloudInit
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CloudInitDataSourceType import CloudInitDataSourceType
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ClusterReference import ClusterReference as AhvConfigClusterReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CpuFeature import CpuFeature
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CreateCdromResponse import CreateCdromResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CreateDiskResponse import CreateDiskResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CreateGpuResponse import CreateGpuResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CreateNicResponse import CreateNicResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CreateSerialPortResponse import CreateSerialPortResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CreateVmResponse import CreateVmResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.Credential import Credential
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CustomKeyValues import CustomKeyValues
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.CustomizeGuestVmResponse import CustomizeGuestVmResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.DataSource import DataSource
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.DeleteCdromResponse import DeleteCdromResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.DeleteDiskResponse import DeleteDiskResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.DeleteGpuResponse import DeleteGpuResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.DeleteNicResponse import DeleteNicResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.DeleteSerialPortResponse import DeleteSerialPortResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.DeleteVmResponse import DeleteVmResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.DetachVmCategoryResponse import DetachVmCategoryResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.Disk import Disk
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.DiskAddress import DiskAddress
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.DiskBusType import DiskBusType
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.EjectCdromResponse import EjectCdromResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.EmulatedNic import EmulatedNic
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.EmulatedNicModel import EmulatedNicModel
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.EnforcementMode import EnforcementMode as AhvConfigEnforcementMode
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GetCdromResponse import GetCdromResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GetDiskResponse import GetDiskResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GetGpuResponse import GetGpuResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GetGuestToolsResponse import GetGuestToolsResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GetNicResponse import GetNicResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GetSerialPortResponse import GetSerialPortResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GetVmCategoriesResponse import GetVmCategoriesResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GetVmOwnershipInfoResponse import GetVmOwnershipInfoResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GetVmResponse import GetVmResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.Gpu import Gpu
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GpuMode import GpuMode as AhvConfigGpuMode
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GpuVendor import GpuVendor as AhvConfigGpuVendor
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GuestCustomization import GuestCustomization
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GuestPowerOptions import GuestPowerOptions
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GuestPowerStateTransitionConfig import GuestPowerStateTransitionConfig
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GuestTools import GuestTools
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GuestToolsInsertConfig import GuestToolsInsertConfig
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GuestToolsInstallConfig import GuestToolsInstallConfig
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.GuestToolsUpgradeConfig import GuestToolsUpgradeConfig
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.HostReference import HostReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ImageReference import ImageReference as AhvConfigImageReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.InsertCdromResponse import InsertCdromResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.InsertVmGuestToolsResponse import InsertVmGuestToolsResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.InstallType import InstallType
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.InstallVmGuestToolsResponse import InstallVmGuestToolsResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.Ipv4Config import Ipv4Config
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.Ipv4Info import Ipv4Info
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.LegacyBoot import LegacyBoot
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ListCdromsResponse import ListCdromsResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ListDisksResponse import ListDisksResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ListGpusResponse import ListGpusResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ListNicsResponse import ListNicsResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ListSerialPortsResponse import ListSerialPortsResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ListVmsResponse import ListVmsResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.MachineType import MachineType as AhvConfigMachineType
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.MigrateNicConfig import MigrateNicConfig
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.MigrateNicResponse import MigrateNicResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.MigrateNicType import MigrateNicType
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.NetworkFunctionChainReference import NetworkFunctionChainReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.NetworkFunctionNicType import NetworkFunctionNicType as AhvConfigNetworkFunctionNicType
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.NgtCapability import NgtCapability
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.Nic import Nic
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.NicNetworkInfo import NicNetworkInfo
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.NicType import NicType as AhvConfigNicType
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.NvramDevice import NvramDevice
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.OwnerReference import OwnerReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.OwnershipInfo import OwnershipInfo
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.PolicyComplianceState import PolicyComplianceState
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.PolicyReference import PolicyReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.PowerCycleVmResponse import PowerCycleVmResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.PowerOffVmResponse import PowerOffVmResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.PowerOnVmResponse import PowerOnVmResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.PowerState import PowerState as AhvConfigPowerState
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ProtectionInfo import ProtectionInfo
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ProtectionInfoReplicationStatus import ProtectionInfoReplicationStatus
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ProtectionPolicyState import ProtectionPolicyState
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ProtectionType import ProtectionType
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.QosConfig import QosConfig
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.RebootPreference import RebootPreference
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.RebootPreferenceSchedule import RebootPreferenceSchedule
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.RebootVmResponse import RebootVmResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.RecoveryPlanState import RecoveryPlanState
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ReleaseIpResponse import ReleaseIpResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ResetVmResponse import ResetVmResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.RevertVmResponse import RevertVmResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.SBDF import SBDF
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ScheduleType import ScheduleType
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.SerialPort import SerialPort
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.ShutdownVmResponse import ShutdownVmResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.SubnetReference import SubnetReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.Sysprep import Sysprep as AhvConfigSysprep
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.UefiBoot import UefiBoot
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.Unattendxml import Unattendxml
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.UninstallVmGuestToolsResponse import UninstallVmGuestToolsResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.UpdateCdromResponse import UpdateCdromResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.UpdateDiskResponse import UpdateDiskResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.UpdateGuestToolsResponse import UpdateGuestToolsResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.UpdateNicResponse import UpdateNicResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.UpdateSerialPortResponse import UpdateSerialPortResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.UpdateVmCategoriesResponse import UpdateVmCategoriesResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.UpdateVmOwnershipInfoResponse import UpdateVmOwnershipInfoResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.UpdateVmResponse import UpdateVmResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.UpgradeVmGuestToolsResponse import UpgradeVmGuestToolsResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.Userdata import Userdata
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.VlanMode import VlanMode as AhvConfigVlanMode
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.Vm import Vm
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.VmCrossClusterMigrateOverrides import VmCrossClusterMigrateOverrides
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.VmCrossClusterMigrateParams import VmCrossClusterMigrateParams
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.VmCrossClusterMigrateWithStorageResponse import VmCrossClusterMigrateWithStorageResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.VmDisk import VmDisk
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.VmDiskContainerReference import VmDiskContainerReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.VmDiskReference import VmDiskReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.VmDiskStorageConfig import VmDiskStorageConfig
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.VmRecoveryPoint import VmRecoveryPoint
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.VmReference import VmReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.VmRevert import VmRevert
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.VmSourceReference import VmSourceReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.VmSourceReferenceEntityType import VmSourceReferenceEntityType
from ntnx_vmm_py_client.Ntnx.vmm.v4.ahv.config.VtpmConfig import VtpmConfig
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.BootDeviceOrder import BootDeviceOrder
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.BootType import BootType
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.CloudInit import CloudInit as ConfigCloudInit
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.CloudInitDataSource import CloudInitDataSource
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.Credentials import Credentials
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.DataSourceReference import DataSourceReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.DiskAdapterType import DiskAdapterType
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.DiskDeviceProperties import DiskDeviceProperties
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.DiskDeviceType import DiskDeviceType
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.GpuMode import GpuMode as ConfigGpuMode
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.GpuVendor import GpuVendor as ConfigGpuVendor
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.IPAssignmentType import IPAssignmentType
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.IPDiscoveredType import IPDiscoveredType
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.IsoMountState import IsoMountState
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.MachineType import MachineType as ConfigMachineType
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.NetworkFunctionNicType import NetworkFunctionNicType as ConfigNetworkFunctionNicType
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.NgtAvailableState import NgtAvailableState
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.NgtEnabledCapability import NgtEnabledCapability
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.NgtState import NgtState
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.NicMacAddress import NicMacAddress
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.NicModel import NicModel
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.NicType import NicType as ConfigNicType
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.PowerState import PowerState as ConfigPowerState
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.PowerStateMechanism import PowerStateMechanism
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.Reference import Reference
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.ReferenceType import ReferenceType
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.Sysprep import Sysprep as ConfigSysprep
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.SysprepInstallType import SysprepInstallType
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.SysprepUnattendXml import SysprepUnattendXml
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.Task import Task
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplate import VMTemplate
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateBootConfig import VMTemplateBootConfig
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateBootDevice import VMTemplateBootDevice
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateDisk import VMTemplateDisk
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateDiskAddress import VMTemplateDiskAddress
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateDiskStorage import VMTemplateDiskStorage
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateFlashMode import VMTemplateFlashMode
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateGpu import VMTemplateGpu
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateGuestCustomization import VMTemplateGuestCustomization
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateGuestPowerStateTransition import VMTemplateGuestPowerStateTransition
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateGuestTools import VMTemplateGuestTools
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateIPAddress import VMTemplateIPAddress
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateNic import VMTemplateNic
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateNutanixGuestTools import VMTemplateNutanixGuestTools
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplatePowerStateMechanism import VMTemplatePowerStateMechanism
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateSerialPort import VMTemplateSerialPort
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateStorage import VMTemplateStorage
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateStorageQosPolicy import VMTemplateStorageQosPolicy
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VMTemplateVNuma import VMTemplateVNuma
from ntnx_vmm_py_client.Ntnx.vmm.v4.config.VlanMode import VlanMode as ConfigVlanMode
from ntnx_vmm_py_client.Ntnx.vmm.v4.error.AppMessage import AppMessage
from ntnx_vmm_py_client.Ntnx.vmm.v4.error.ErrorResponse import ErrorResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.error.SchemaValidationError import SchemaValidationError
from ntnx_vmm_py_client.Ntnx.vmm.v4.error.SchemaValidationErrorMessage import SchemaValidationErrorMessage
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.CancelPlacementTasks import CancelPlacementTasks
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.CategoryReference import CategoryReference as ImagesCategoryReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ClusterEntityFilter import ClusterEntityFilter
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ClusterIdList import ClusterIdList
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ClusterImages import ClusterImages
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ClusterRateLimitStatus import ClusterRateLimitStatus
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ClusterReference import ClusterReference as ImagesClusterReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ComplianceStatus import ComplianceStatus
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.EffectiveRateLimit import EffectiveRateLimit
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.EnforcementMode import EnforcementMode as ImagesEnforcementMode
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.EnforcementState import EnforcementState
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.EntityFilter import EntityFilter
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.FilterMatchType import FilterMatchType
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.Image import Image
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ImageApiResponse import ImageApiResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ImageCategoriesApiResponse import ImageCategoriesApiResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ImageChecksum import ImageChecksum
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ImageChecksumType import ImageChecksumType
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ImageClusterLocationListApiResponse import ImageClusterLocationListApiResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ImageListApiResponse import ImageListApiResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ImagePlacementPolicyListApiResponse import ImagePlacementPolicyListApiResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ImageReference import ImageReference as ImagesImageReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ImageType import ImageType
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ImagesTaskApiResponse import ImagesTaskApiResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.PlacementPolicy import PlacementPolicy
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.PlacementPolicyApiResponse import PlacementPolicyApiResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.PlacementPolicyListApiResponse import PlacementPolicyListApiResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.PlacementPolicyReference import PlacementPolicyReference
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.PlacementPolicyStatus import PlacementPolicyStatus
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.PlacementType import PlacementType
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.RateLimit import RateLimit
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.RateLimitApiResponse import RateLimitApiResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.RateLimitIdList import RateLimitIdList
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.RateLimitListApiResponse import RateLimitListApiResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.RateLimitTask import RateLimitTask
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.RateLimitTaskListApiResponse import RateLimitTaskListApiResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.ResolveRateLimitsApiResponse import ResolveRateLimitsApiResponse
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.UrlSource import UrlSource
from ntnx_vmm_py_client.Ntnx.vmm.v4.images.VmDiskSource import VmDiskSource
from ntnx_vmm_py_client.api_response import ApiResponse
