# -*- coding: utf-8 -*-

# ----------------------------------------------------------------------------------------------------------------------
#  Copyright (c) 2023. Antonio Bulgheroni.
#  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#  documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
#  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
#  permit persons to whom the Software is furnished to do so, subject to the following conditions:
#  The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
#  Software.
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
#  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
#  OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
#  OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# ----------------------------------------------------------------------------------------------------------------------

# Form implementation generated from reading ui file 'S:\software-dev\autologbook-dev\autologbook\ui\about_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.setWindowModality(QtCore.Qt.NonModal)
        About.resize(283, 258)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/icons8-logbook-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        About.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(About)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(About)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About Autologbook"))
        self.label.setText(_translate("About",
                                      "<html><head/><body><p align=\"center\"><img src=\":/resources/icons8-logbook-64.png\"/></p><p\n"
                                      "       align=\"center\"><br/></p><p align=\"center\">AUTOLOGBOOK v0.1.2</p><p\n"
                                      "       align=\"center\">A script for automatic logbook generation in microscopy</p><p align=\"center\">GitHub\n"
                                      "       <a href=\"https://github.com/abulgher/autologbook\"><span style=\" text-decoration:\n"
                                      "       underline; color:#0000ff;\">Source Code</span></a></p><p align=\"center\">(C)\n"
                                      "       Antonio Bulgheroni - 2022</p><p align=\"center\"><br/><a href=\"https://icons8.com/icon/pNYOTp5DinZ3/copy\"><span\n"
                                      "       style=\" text-decoration: underline; color:#0000ff;\">Copy</span></a> icon by <a href=\"https://icons8.com\"><span\n"
                                      "       style=\" text-decoration: underline; color:#0000ff;\">Icons8</span></a></p></body></html>\n"
                                      "      "))


from . import resource_rc
