
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-06T11:11:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "be9abf5d01daface1e59644fa0ca908f3af9c411",
 "version": "v2.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
