# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Sequence

from pydantic import BaseModel


class Model(BaseModel):
    y_21: Sequence[float]
    y_23: Sequence[float]
    y_24: Sequence[float]
    g_2: Sequence[float]
    y_2: Sequence[float]
