# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Sequence

from pydantic import BaseModel


class Model(BaseModel):
    y_1: Sequence[float]
    y_11: Sequence[float]
    y_14: Sequence[float]
    g_1: Sequence[float]
    y_12: Sequence[float]
