
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-06T16:14:38-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8ec441f70c5271e6cfd17668ea2ad62d8a38c69",
 "version": "0.2.63.post0.dev71"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
