# coding: utf-8


"""
IGNORE:
    Nutanix Prism Versioned APIs

    Task Management, Category Associations, Prism Central DR, Alerts, Alert policies, Events and Audits  # noqa: E501

    OpenAPI spec version: 4.0.2-alpha-1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
IGNORE
"""
import pprint
import json
import ast
import re  # noqa: F401

import six
from ntnx_prism_py_client.Ntnx.common.v1.response.ApiLink import ApiLink  # noqa: F401,E501
from ntnx_prism_py_client.Ntnx.common.v1.response.ExternalizableAbstractModel import ExternalizableAbstractModel  # noqa: F401,E501
from ntnx_prism_py_client.Ntnx.prism.v4.alerts.RootCauseAnalysis import RootCauseAnalysis  # noqa: F401,E501
from ntnx_prism_py_client.Ntnx.prism.v4.alerts.SeverityTrail import SeverityTrail  # noqa: F401,E501
from ntnx_prism_py_client.Ntnx.prism.v4.common.AlertEntityReference import AlertEntityReference  # noqa: F401,E501
from ntnx_prism_py_client.Ntnx.prism.v4.common.EntityReference import EntityReference  # noqa: F401,E501
from ntnx_prism_py_client.Ntnx.prism.v4.common.ImpactType import ImpactType  # noqa: F401,E501
from ntnx_prism_py_client.Ntnx.prism.v4.common.MetricDetail import MetricDetail  # noqa: F401,E501
from ntnx_prism_py_client.Ntnx.prism.v4.common.Parameter import Parameter  # noqa: F401,E501
from ntnx_prism_py_client.Ntnx.prism.v4.common.Severity import Severity  # noqa: F401,E501

"""
IGNORE:
NOTE: This class is auto generated by the swagger code generator program.

Do not edit the class manually.
IGNORE
"""


class Alert(ExternalizableAbstractModel):
    """Alert - a model defined in Swagger"""
    """
    IGNORE:
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    IGNORE
    """ # noqa: E501
    swagger_types = {
        'acknowledged': 'bool',
        'acknowledged_by_username': 'str',
        'acknowledged_timestamp': 'int',
        'auto_resolved': 'bool',
        'resolved': 'bool',
        'resolved_by_username': 'str',
        'resolved_timestamp': 'int',
        'source_entity': 'prism.v4.common.AlertEntityReference',
        'affected_entities': 'list[prism.v4.common.EntityReference]',
        'severity_trails': 'list[prism.v4.alerts.SeverityTrail]',
        'metric_details': 'list[prism.v4.common.MetricDetail]',
        'title': 'str',
        'alert_type': 'str',
        'classifications': 'list[str]',
        'cluster_uuid': 'str',
        'creation_timestamp': 'int',
        'impact_types': 'list[prism.v4.common.ImpactType]',
        'last_updated_timestamp': 'int',
        'message': 'str',
        'originating_cluster_uuid': 'str',
        'severity': 'prism.v4.common.Severity',
        'user_defined': 'bool',
        'parameters': 'list[prism.v4.common.Parameter]',
        'service_name': 'str',
        'root_cause_analysis': 'list[prism.v4.alerts.RootCauseAnalysis]',
        'ext_id': 'str',
        'links': 'list[common.v1.response.ApiLink]',
        'tenant_id': 'str',
        '_reserved': 'dict(str, object)',
        '_object_type': 'str',
        '_unknown_fields': 'dict(str, object)',
    }

    attribute_map = {
        'acknowledged': 'acknowledged',
        'acknowledged_by_username': 'acknowledgedByUsername',
        'acknowledged_timestamp': 'acknowledgedTimestamp',
        'auto_resolved': 'autoResolved',
        'resolved': 'resolved',
        'resolved_by_username': 'resolvedByUsername',
        'resolved_timestamp': 'resolvedTimestamp',
        'source_entity': 'sourceEntity',
        'affected_entities': 'affectedEntities',
        'severity_trails': 'severityTrails',
        'metric_details': 'metricDetails',
        'title': 'title',
        'alert_type': 'alertType',
        'classifications': 'classifications',
        'cluster_uuid': 'clusterUUID',
        'creation_timestamp': 'creationTimestamp',
        'impact_types': 'impactTypes',
        'last_updated_timestamp': 'lastUpdatedTimestamp',
        'message': 'message',
        'originating_cluster_uuid': 'originatingClusterUUID',
        'severity': 'severity',
        'user_defined': 'userDefined',
        'parameters': 'parameters',
        'service_name': 'serviceName',
        'root_cause_analysis': 'rootCauseAnalysis',
        'ext_id': 'extId',
        'links': 'links',
        'tenant_id': 'tenantId',
        '_reserved': '$reserved',
        '_object_type': '$objectType',
        '_unknown_fields': '$unknownFields',
    }



    def __init__(self, acknowledged=False, acknowledged_by_username=None, acknowledged_timestamp=None, auto_resolved=False, resolved=False, resolved_by_username=None, resolved_timestamp=None, source_entity=None, affected_entities=None, severity_trails=None, metric_details=None, title=None, alert_type=None, classifications=None, cluster_uuid=None, creation_timestamp=None, impact_types=None, last_updated_timestamp=None, message=None, originating_cluster_uuid=None, severity=None, user_defined=False, parameters=None, service_name=None, root_cause_analysis=None, ext_id=None, links=None, tenant_id=None, *args, **kwargs):  # noqa: E501
        """Alert - a model defined in Swagger
            
        """
        ExternalizableAbstractModel.__init__(self, ext_id, links, tenant_id, *args, **kwargs)
        self.__acknowledged = None
        self.__acknowledged_by_username = None
        self.__acknowledged_timestamp = None
        self.__auto_resolved = None
        self.__resolved = None
        self.__resolved_by_username = None
        self.__resolved_timestamp = None
        self.__source_entity = None
        self.__affected_entities = None
        self.__severity_trails = None
        self.__metric_details = None
        self.__title = None
        self.__alert_type = None
        self.__classifications = None
        self.__cluster_uuid = None
        self.__creation_timestamp = None
        self.__impact_types = None
        self.__last_updated_timestamp = None
        self.__message = None
        self.__originating_cluster_uuid = None
        self.__severity = None
        self.__user_defined = None
        self.__parameters = None
        self.__service_name = None
        self.__root_cause_analysis = None
        self.discriminator = None
        if acknowledged is not None:
            self.__acknowledged = acknowledged
        if acknowledged_by_username is not None:
            self.__acknowledged_by_username = acknowledged_by_username
        if acknowledged_timestamp is not None:
            self.__acknowledged_timestamp = acknowledged_timestamp
        if auto_resolved is not None:
            self.__auto_resolved = auto_resolved
        if resolved is not None:
            self.__resolved = resolved
        if resolved_by_username is not None:
            self.__resolved_by_username = resolved_by_username
        if resolved_timestamp is not None:
            self.__resolved_timestamp = resolved_timestamp
        if source_entity is not None:
            self.__source_entity = source_entity
        if affected_entities is not None:
            self.__affected_entities = affected_entities
        if severity_trails is not None:
            self.__severity_trails = severity_trails
        if metric_details is not None:
            self.__metric_details = metric_details
        if title is not None:
            self.__title = title
        if alert_type is not None:
            self.__alert_type = alert_type
        if classifications is not None:
            self.__classifications = classifications
        if cluster_uuid is not None:
            self.__cluster_uuid = cluster_uuid
        if creation_timestamp is not None:
            self.__creation_timestamp = creation_timestamp
        if impact_types is not None:
            self.__impact_types = impact_types
        if last_updated_timestamp is not None:
            self.__last_updated_timestamp = last_updated_timestamp
        if message is not None:
            self.__message = message
        if originating_cluster_uuid is not None:
            self.__originating_cluster_uuid = originating_cluster_uuid
        if severity is not None:
            self.__severity = severity
        if user_defined is not None:
            self.__user_defined = user_defined
        if parameters is not None:
            self.__parameters = parameters
        if service_name is not None:
            self.__service_name = service_name
        if root_cause_analysis is not None:
            self.__root_cause_analysis = root_cause_analysis

    def _initialize_object_type(self):
        return 'prism.v4.alerts.Alert'

    def _initialize_fq_object_type(self):
        return 'prism.v4.r0.a1.alerts.Alert'


    @property
    def acknowledged(self):
        """`{ bool }`
            \nField specifies if the alert is acknowledged or not.
        """ # noqa: E501
        return self.__acknowledged

    @acknowledged.setter
    def acknowledged(self, acknowledged):

        self.__acknowledged = acknowledged

    @property
    def acknowledged_by_username(self):
        """`{ str }`
            \nName of the user who acknowledged this alert.
        """ # noqa: E501
        return self.__acknowledged_by_username

    @acknowledged_by_username.setter
    def acknowledged_by_username(self, acknowledged_by_username):

        self.__acknowledged_by_username = acknowledged_by_username

    @property
    def acknowledged_timestamp(self):
        """`{ int }`
            \nThe timestamp in microseconds when the alert was acknowledged.
        """ # noqa: E501
        return self.__acknowledged_timestamp

    @acknowledged_timestamp.setter
    def acknowledged_timestamp(self, acknowledged_timestamp):

        self.__acknowledged_timestamp = acknowledged_timestamp

    @property
    def auto_resolved(self):
        """`{ bool }`
            \nField specifies if the alert is auto resolved or not.
        """ # noqa: E501
        return self.__auto_resolved

    @auto_resolved.setter
    def auto_resolved(self, auto_resolved):

        self.__auto_resolved = auto_resolved

    @property
    def resolved(self):
        """`{ bool }`
            \nField specifies if the alert is resolved or not.
        """ # noqa: E501
        return self.__resolved

    @resolved.setter
    def resolved(self, resolved):

        self.__resolved = resolved

    @property
    def resolved_by_username(self):
        """`{ str }`
            \nName of the user who resolved this alert.
        """ # noqa: E501
        return self.__resolved_by_username

    @resolved_by_username.setter
    def resolved_by_username(self, resolved_by_username):

        self.__resolved_by_username = resolved_by_username

    @property
    def resolved_timestamp(self):
        """`{ int }`
            \nThe timestamp in microseconds when the alert was resolved.
        """ # noqa: E501
        return self.__resolved_timestamp

    @resolved_timestamp.setter
    def resolved_timestamp(self, resolved_timestamp):

        self.__resolved_timestamp = resolved_timestamp

    @property
    def source_entity(self):
        """`{ prism.v4.common.AlertEntityReference }`
            
        """ # noqa: E501
        return self.__source_entity

    @source_entity.setter
    def source_entity(self, source_entity):

        self.__source_entity = source_entity

    @property
    def affected_entities(self):
        """`{ list[prism.v4.common.EntityReference] }`
            \nList of all entities that are affected by the alert.
        """ # noqa: E501
        return self.__affected_entities

    @affected_entities.setter
    def affected_entities(self, affected_entities):

        self.__affected_entities = affected_entities

    @property
    def severity_trails(self):
        """`{ list[prism.v4.alerts.SeverityTrail] }`
            \nContains information on the severity change history for alerts. If an alert was de-duplicated without change in severity, then no trail will be present.
        """ # noqa: E501
        return self.__severity_trails

    @severity_trails.setter
    def severity_trails(self, severity_trails):

        self.__severity_trails = severity_trails

    @property
    def metric_details(self):
        """`{ list[prism.v4.common.MetricDetail] }`
            \nDetails of the metric for a metric-based event.
        """ # noqa: E501
        return self.__metric_details

    @metric_details.setter
    def metric_details(self, metric_details):

        self.__metric_details = metric_details

    @property
    def title(self):
        """`{ str }`
            \nTitle of the alert.
        """ # noqa: E501
        return self.__title

    @title.setter
    def title(self, title):

        self.__title = title

    @property
    def alert_type(self):
        """`{ str }`
            \nA preconfigured or dynamically generated unique value for each alert type. For example, A1128  for storage pool space exceeded alerts.
        """ # noqa: E501
        return self.__alert_type

    @alert_type.setter
    def alert_type(self, alert_type):

        self.__alert_type = alert_type

    @property
    def classifications(self):
        """`{ list[str] }`
            \nVarious categories into which this alert type can be classified into. For example, Hardware, Storage, License and so on.
        """ # noqa: E501
        return self.__classifications

    @classifications.setter
    def classifications(self, classifications):

        self.__classifications = classifications

    @property
    def cluster_uuid(self):
        """`{ str }`
            \nCluster UUID associated with the source entity of the alert.
        """ # noqa: E501
        return self.__cluster_uuid

    @cluster_uuid.setter
    def cluster_uuid(self, cluster_uuid):
        if cluster_uuid is not None and not re.search('^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$', cluster_uuid):  # noqa: E501
            raise ValueError(r"Invalid value for `cluster_uuid`, must be a follow pattern or equal to `/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/`")  # noqa: E501

        self.__cluster_uuid = cluster_uuid

    @property
    def creation_timestamp(self):
        """`{ int }`
            \nTimestamp in microseconds when the alert was created.
        """ # noqa: E501
        return self.__creation_timestamp

    @creation_timestamp.setter
    def creation_timestamp(self, creation_timestamp):

        self.__creation_timestamp = creation_timestamp

    @property
    def impact_types(self):
        """`{ list[prism.v4.common.ImpactType] }`
            \nThe impact this alert/event will have on the system. For example, availability, performance, capacity and so on.
        """ # noqa: E501
        return self.__impact_types

    @impact_types.setter
    def impact_types(self, impact_types):

        self.__impact_types = impact_types

    @property
    def last_updated_timestamp(self):
        """`{ int }`
            \nTimestamp in microseconds when the alert was last updated.
        """ # noqa: E501
        return self.__last_updated_timestamp

    @last_updated_timestamp.setter
    def last_updated_timestamp(self, last_updated_timestamp):

        self.__last_updated_timestamp = last_updated_timestamp

    @property
    def message(self):
        """`{ str }`
            \nAdditional message associated with the alert.
        """ # noqa: E501
        return self.__message

    @message.setter
    def message(self, message):

        self.__message = message

    @property
    def originating_cluster_uuid(self):
        """`{ str }`
            \nCluster UUID associated with the cluster where the alert was first raised.
        """ # noqa: E501
        return self.__originating_cluster_uuid

    @originating_cluster_uuid.setter
    def originating_cluster_uuid(self, originating_cluster_uuid):
        if originating_cluster_uuid is not None and not re.search('^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$', originating_cluster_uuid):  # noqa: E501
            raise ValueError(r"Invalid value for `originating_cluster_uuid`, must be a follow pattern or equal to `/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/`")  # noqa: E501

        self.__originating_cluster_uuid = originating_cluster_uuid

    @property
    def severity(self):
        """`{ prism.v4.common.Severity }`
            
        """ # noqa: E501
        return self.__severity

    @severity.setter
    def severity(self, severity):

        self.__severity = severity

    @property
    def user_defined(self):
        """`{ bool }`
            \nFlag to indicate if the alert was generated from a user defined alert policy.
        """ # noqa: E501
        return self.__user_defined

    @user_defined.setter
    def user_defined(self, user_defined):

        self.__user_defined = user_defined

    @property
    def parameters(self):
        """`{ list[prism.v4.common.Parameter] }`
            \nAdditional parameters associated with the alert. These parameters can be used to indicate custom key-value pairs for a given alert instance. For example, Service down in Prism Central alert can have the service name as a parameter.
        """ # noqa: E501
        return self.__parameters

    @parameters.setter
    def parameters(self, parameters):

        self.__parameters = parameters

    @property
    def service_name(self):
        """`{ str }`
            \nThe service that raised the alert. For internal Nutanix services, this value is set to \"Nutanix\".
        """ # noqa: E501
        return self.__service_name

    @service_name.setter
    def service_name(self, service_name):

        self.__service_name = service_name

    @property
    def root_cause_analysis(self):
        """`{ list[prism.v4.alerts.RootCauseAnalysis] }`
            \nPossible causes, resolutions and additional details to troubleshoot this alert.
        """ # noqa: E501
        return self.__root_cause_analysis

    @root_cause_analysis.setter
    def root_cause_analysis(self, root_cause_analysis):

        self.__root_cause_analysis = root_cause_analysis

    def _to_dict(self, sanitize):
        """
        Returns the model properties as a dict. Omits None properties based on the provided "sanitize" parameter.
        :param bool sanitize
        """

        result = {}

        for attr, attr_type in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x._to_dict(sanitize) if hasattr(x, "_to_dict") else x,
                    value
                ))
            elif hasattr(value, "_to_dict"):
                result[attr] = value._to_dict(sanitize)
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1]._to_dict(sanitize))
                    if hasattr(item[1], "_to_dict") else item,
                    six.iteritems(value)
                ))
            else:
                if sanitize:
                    if value is not None:
                        result[attr] = value
                else:
                    result[attr] = value
        if issubclass(Alert, dict):
            for key, value in six.iteritems(self):
                result[key] = value

        return result

    def to_dict(self):
        """Returns the model properties as a dict"""
        return self._to_dict(False)

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self._to_dict(True))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Alert):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other

