################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.md", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Development Status :: 5 - Production/Stable",
		"Environment :: Console",
		"License :: OSI Approved :: Apache Software License",
		"Programming Language :: Python :: 3",
	],
	description = "This python module provides a variety of essential functions for implementing versatile programs using the console. (Please have a look at the documentation for details.)",
	include_package_data = True,
	install_requires = [
		# "msvcrt",
	],
	keywords = [
		"console",
		"terminal",
		"colors",
		"stdin",
	],
	license = "Apache2",
	name = "jk_console",
	package_data = {
		"": [
		],
	},
	packages = [
		"jk_console",
		"jk_console.viewport",
		"jk_console.demo",
	],
	scripts = [
	],
	version = '0.2023.2.8',
	zip_safe = False,
	long_description = readme(),
	long_description_content_type = "text/markdown",
)
