VERSION_YEAR = 2023
VERSION_MONTH = int('02')
VERSION_DAY = int('09')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('17')
MAJOR_VERSION = 0
MINOR_VERSION = 25
PATCH_VERSION = 202302090717
version_date = '2023/02/09 07:17'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
