
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-07T09:16:20-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "25a9ec6dc55ea3666c27c5e7928252248ed1cf0f",
 "version": "0.2.63.post0.dev80"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
