# Generated by Django 3.2.16 on 2023-02-06 05:55

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('giant_events', '0005_auto_20230206_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giant_events_content', slotname='event_content', to='cms.placeholder'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giant_events', to='giant_events.location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='giant_events', to='giant_events.Tag', verbose_name='Tags'),
        ),
    ]
