from umls_tools.umls_column import UmlsColumn


class SemanticNetworkColumn(UmlsColumn):

    ABR = "abbrevation"
    BTS = "size of bytes"
    CLS = "number of columns"
    COL = "field name"
    DEF = "definition"
    DES = "short description"
    DUMMY = "dummy"
    EX = "examples"
    FIL = "file name(s)"
    FMT = "format"
    LS = "link status"
    NH = "non-human flag"
    REF = "cross reference to documentation"
    RIN = "relation inverse"
    RL = "relation name"
    RTN = "relation tree number"
    RT = "record type"
    RWS = "number of rows"
    STN = "semantic type tree number"
    STY = "semantic type name"
    STY1 = "first type name"
    STY2 = "second type name"
    STY_RL = "semantic type or relation name"
    STY_RL1 = "first type or relation"
    STY_RL2 = "second type or relation"
    STN_RTN = "type or relation tree identifier"
    UI = "unique identifier"
    UI1 = "first unique identifier"
    UI2 = "second unique identifier"
    UI3 = "third unique identifier"
    UN = "usage note"
