# coding: utf-8
# file generated by setuptools_scm + setup.py
# don't change, don't track in version control
git_hash = b'\x0c\x99,\x84'
full_git_hash = '0c992c846af9d7207b24c4d1b9fc657fe20a9819'
git_branch = 'HEAD'
dirty = False
