
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-09T00:35:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "21109e8082ec22b1a30f066bc6922d246e8e2022",
 "version": "0.2.63.post0.dev125"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
