# Generated by Django 2.2.4 on 2020-03-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu_base', '0011_xss'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakiResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Do not include the host portion of the URL', max_length=500, verbose_name='Finti Endpoint URL')),
                ('method', models.CharField(default='GET', help_text='GET, POST, PUT, PATCH, DELETE, etc', max_length=10, verbose_name='Request Method')),
                ('parameters', models.TextField(blank=True, default=None, null=True, verbose_name='Parameters provided to the API endpoint')),
                ('payload', models.TextField(blank=True, default=None, help_text='Use only if the endpoint accepts JSON data', null=True, verbose_name='JSON body provided as POST data')),
                ('headers', models.TextField(blank=True, default=None, null=True, verbose_name='Headers sent with request')),
                ('json_response', models.TextField(blank=True, default=None, help_text='The full unedited response from Finti', null=True, verbose_name='JSON body provided as POST data')),
                ('hash_identifier', models.CharField(help_text='Allows a unique lookup to a specific URL and parameter set', max_length=100, verbose_name='Unique Identifier')),
            ],
        ),
    ]
