# Generated by Django 3.2.11 on 2022-02-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu_base', '0024_alter_audit_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
