from enum import Enum


class HubPlatform(Enum):
    BLING = 'BLING'
    NUVEMSHOP = 'NUVEMSHOP'
    SHOPIFY = 'SHOPIFY'
    TINY = 'TINY'
    WOOCOMMERCE = 'WOOCOMMERCE'
    VTEX = 'VTEX'
    OMNIK_ON_STORES = 'OMNIK_ON_STORES'
    UNILEVER_MEU_MERCADO_EM_CASA = 'UNILEVER_MEU_MERCADO_EM_CASA'
    JCPM = 'JCPM'
    YAMI = 'YAMI'
    MPMS_JCC = 'MPMS_JCC'
    GESTOR_RETAIL_SYSTEM = 'GESTOR_RETAIL_SYSTEM'
    MICROVIX = 'MICROVIX'
    LUPO = 'LUPO'
    MULTICOISAS = 'MULTICOISAS'
    EMILLENNIUM = 'EMILLENNIUM'
