
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-06T17:14:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e52804acc057e1de3d92b93c12a20fff19f1e65f",
 "version": "5.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
