# This file automatically generated by
#    /Users/couchbase/jenkins/workspace/python/sdk/python-scripted-build-pipeline/py-client/./couchbase_version.py
# at
#    2023-02-09 16:04:20.448250
__version__ = '4.1.2rc2'