# Generated by Django 4.0.4 on 2022-12-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obpages", "0006_curatedcontentitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbacknote",
            name="spam_score",
            field=models.FloatField(
                blank=True,
                help_text=(
                    "How likely the note is spam. 0 means more likely, 1 means less."
                ),
                null=True,
            ),
        ),
    ]
