
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-02T15:00:02-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "23cadc6b7bff4d28918b2d29591af6fa9823148c",
 "version": "0.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
