
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-09T09:49:50-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "fbf0fb5b78220d7a3cae07bbd35503ccae47aa77",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
