
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-08T12:01:12-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b052a0ccdf032ca2e5f8a650e7d5a4d8851a53fd",
 "version": "4.9.63"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
