
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-06T21:46:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ec78b6a0ad767e8a9416facc9228b5f9360f2e2",
 "version": "0.0.7.dev20230208"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
