# Generated by Django 3.2.5 on 2021-07-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu_base', '0023_auto_20210706_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='comments',
            field=models.TextField(blank=True, default=None, help_text='Comments about the event', null=True),
        ),
    ]
