# Generated by Django 2.2.15 on 2020-12-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psu_base", "0019_error_stacktrace"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="reference_code",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=60, null=True
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="reference_id",
            field=models.IntegerField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="app_code",
            field=models.CharField(
                db_index=True,
                help_text="Application that this audit belongs to.",
                max_length=15,
                verbose_name="Application Code",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="event_code",
            field=models.CharField(
                db_index=True,
                help_text="This string should uniquely identify the type of event",
                max_length=80,
            ),
        ),
    ]
