
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-07T14:35:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2bdea22a3c3fe8618d7e7166af421e1484b44090",
 "version": "1.18.2.post0.dev12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
