
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-06T18:29:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "da0973abd1b12b7ea9b52d6efa171facae3c4187",
 "version": "0.1.1.dev20230208"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
