
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-26T16:42:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d8eb7e63085be9aa340dd2669e4fb0a85bdfe793",
 "version": "0.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
