
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-08T15:12:36-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "614cfebbaad18f7f7659d1e63a3d1b3be57780c1",
 "version": "0.2.63.post0.dev116"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
