
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-09T15:46:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3b7b80ebd1fb127e16513f1c639311e56c6d649",
 "version": "0.3.11.post3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
