# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Boundingbox2D(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Boundingbox2D()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBoundingbox2D(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Boundingbox2D
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Boundingbox2D
    def PointMin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from seerep.fb.Point2D import Point2D
            obj = Point2D()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Boundingbox2D
    def PointMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from seerep.fb.Point2D import Point2D
            obj = Point2D()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Start(builder): builder.StartObject(2)
def Boundingbox2DStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddPointMin(builder, pointMin): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pointMin), 0)
def Boundingbox2DAddPointMin(builder, pointMin):
    """This method is deprecated. Please switch to AddPointMin."""
    return AddPointMin(builder, pointMin)
def AddPointMax(builder, pointMax): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(pointMax), 0)
def Boundingbox2DAddPointMax(builder, pointMax):
    """This method is deprecated. Please switch to AddPointMax."""
    return AddPointMax(builder, pointMax)
def End(builder): return builder.EndObject()
def Boundingbox2DEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)