from umls_tools.umls_column import UmlsColumn


class MetathesaurusColumn(UmlsColumn):

    ATUI = "Unique identifier for attribute."
    AUI = "Unique identifier for atom"
    AUI1 = "Unique identifier for first atom"
    AUI2 = "Unique identifier for second atom"
    AV = "Average Length, Characters"
    BTS = "Size in Bytes"
    CLS = "Number of columns"
    CODE = "Unique Identifier or code for string in source"
    COL = "Column of data element name"
    CUI = "Unique identifier for concept"
    CUI1 = "Unique identifier for first concept"
    CUI2 = "Unique identifier for second concept"
    CVF = "Content view flag"
    DEF = "Definition"
    DES = "Descriptive Name"
    DIR = "Source asserted directionality flag"
    DTY = "SQL-92 data type for this column"
    FIL = "Physical filename"
    FMT = "Comma separated list of COL"
    ISPREF = "Indicates whether AUI is preferred"
    LAT = "Language of Term(s)"
    LUI = "Unique identifier for term"
    MAX = "Maximum length"
    MIN = "Minimum length"
    RANK = "Termgroup ranking"
    REF = "Documentation Section Number"
    REL = "Relationship label"
    RELA = "Additional relationship label"
    RG = "Relationship group"
    RUI = "Unique identifier for relationship"
    RWS = "Number of rows"
    SAB = "Source abbreviation"
    SAUI = "Source asserted atom identifier"
    SCUI = "Source asserted concept identifier"
    SDUI = "Source asserted descriptor identifier"
    SL = "Source of relationship labels"
    SRL = "Source Restriction Level"
    SRUI = "Source attributed relationship identifier"
    STN = "semantic type tree number"
    STR = "String"
    STT = "String type"
    STY = "semantic type name"
    STYPE1 = "The name of the column in MRCONSO.RRF that contains the first identifier to which the relationship is attached"
    STYPE2 = "The name of the column in MRCONSO.RRF that contains the second identifier to which the relationship is attached"
    STYPE = "The name of the column in MRCONSO.RRF or MRREL.RRF that contains the identifier to which the attribute is attached"
    SUI = "Unique identifier for string"
    SUPPRESS = "Suppressible flag"
    TS = "Term status"
    TTY = "Term type in source"
    TUI = "unique identifier of semantic type"
