# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tecton_proto/validation/validator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tecton_proto.args import fco_args_pb2 as tecton__proto_dot_args_dot_fco__args__pb2
from tecton_proto.args import entity_pb2 as tecton__proto_dot_args_dot_entity__pb2
from tecton_proto.args import virtual_data_source_pb2 as tecton__proto_dot_args_dot_virtual__data__source__pb2
from tecton_proto.common import spark_schema_pb2 as tecton__proto_dot_common_dot_spark__schema__pb2
from tecton_proto.data import fco_pb2 as tecton__proto_dot_data_dot_fco__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'tecton_proto/validation/validator.proto\x12\x17tecton_proto.validation\x1a tecton_proto/args/fco_args.proto\x1a\x1etecton_proto/args/entity.proto\x1a+tecton_proto/args/virtual_data_source.proto\x1a&tecton_proto/common/spark_schema.proto\x1a\x1btecton_proto/data/fco.proto\"L\n\x17\x45ntityValidationRequest\x12\x31\n\x04\x61rgs\x18\x01 \x01(\x0b\x32\x1d.tecton_proto.args.EntityArgsR\x04\x61rgs\"\xe7\x01\n\x1b\x44\x61taSourceValidationRequest\x12<\n\x04\x61rgs\x18\x01 \x01(\x0b\x32(.tecton_proto.args.VirtualDataSourceArgsR\x04\x61rgs\x12\x43\n\x0c\x62\x61tch_schema\x18\x02 \x01(\x0b\x32 .tecton_proto.common.SparkSchemaR\x0b\x62\x61tchSchema\x12\x45\n\rstream_schema\x18\x03 \x01(\x0b\x32 .tecton_proto.common.SparkSchemaR\x0cstreamSchema\"\x8b\x02\n\x11ValidationRequest\x12n\n\x19\x65ntity_validation_request\x18\x01 \x01(\x0b\x32\x30.tecton_proto.validation.EntityValidationRequestH\x00R\x17\x65ntityValidationRequest\x12{\n\x1e\x64\x61ta_source_validation_request\x18\x02 \x01(\x0b\x32\x34.tecton_proto.validation.DataSourceValidationRequestH\x00R\x1b\x64\x61taSourceValidationRequestB\t\n\x07requestB\x19\n\x15\x63om.tecton.validationP\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tecton_proto.validation.validator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025com.tecton.validationP\001'
  _ENTITYVALIDATIONREQUEST._serialized_start=248
  _ENTITYVALIDATIONREQUEST._serialized_end=324
  _DATASOURCEVALIDATIONREQUEST._serialized_start=327
  _DATASOURCEVALIDATIONREQUEST._serialized_end=558
  _VALIDATIONREQUEST._serialized_start=561
  _VALIDATIONREQUEST._serialized_end=828
# @@protoc_insertion_point(module_scope)
