# Generated by Django 2.2.6 on 2020-07-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu_base', '0014_auto_20200528_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='disable_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='enable_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
