# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '1.0.5'
git_version = '56f87a8b2dc41f3b727f860c1f9efc3d74f479d7'
