# Generated by Django 2.2.15 on 2020-08-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psu_base", "0015_auto_20200713_0949"),
    ]

    operations = [
        migrations.AddField(
            model_name="error",
            name="debug_info",
            field=models.CharField(
                blank=True, help_text="Additional debug info", max_length=128, null=True
            ),
        ),
    ]
