# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Sequence

from pydantic import BaseModel


class Model(BaseModel):
    f_2: Sequence
    f_6: Sequence
    f_7: Sequence
    f_9: Sequence
    obj: Sequence
