# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Sequence

from pydantic import BaseModel, Field


class Model(BaseModel):
    x_shared: Sequence[float] = Field(
        ...,
        description="NDArray[complex128] = [1.+0.j 1.+0.j 1.+0.j 1.+0.j]",
        max_items=4,
        min_items=4,
    )
