# coding: utf-8


"""
IGNORE:
    Nutanix Prism Versioned APIs

    Task Management, Category Associations, Prism Central DR, Alerts, Alert policies, Events and Audits  # noqa: E501

    OpenAPI spec version: 4.0.2-alpha-1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
IGNORE
"""
import pprint
import json
import ast
import re  # noqa: F401

import six
from ntnx_prism_py_client.Ntnx.prism.v4.common.ImpactType import ImpactType  # noqa: F401,E501
from ntnx_prism_py_client.Ntnx.prism.v4.common.Severity import Severity  # noqa: F401,E501

"""
IGNORE:
NOTE: This class is auto generated by the swagger code generator program.

Do not edit the class manually.
IGNORE
"""


class EmailConfigurationRule(object):
    """EmailConfigurationRule - a model defined in Swagger"""
    """
    IGNORE:
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    IGNORE
    """ # noqa: E501
    swagger_types = {
        'cluster_uuids': 'list[str]',
        'impact_types': 'list[prism.v4.common.ImpactType]',
        'include_global_email_contact_list': 'bool',
        'match_phrases': 'list[str]',
        'recipients': 'list[str]',
        'severities': 'list[prism.v4.common.Severity]',
        '_reserved': 'dict(str, object)',
        '_object_type': 'str',
        '_unknown_fields': 'dict(str, object)',
    }

    attribute_map = {
        'cluster_uuids': 'clusterUuids',
        'impact_types': 'impactTypes',
        'include_global_email_contact_list': 'includeGlobalEmailContactList',
        'match_phrases': 'matchPhrases',
        'recipients': 'recipients',
        'severities': 'severities',
        '_reserved': '$reserved',
        '_object_type': '$objectType',
        '_unknown_fields': '$unknownFields',
    }



    def __init__(self, cluster_uuids=None, impact_types=None, include_global_email_contact_list=False, match_phrases=None, recipients=None, severities=None, *args, **kwargs):  # noqa: E501
        """EmailConfigurationRule - a model defined in Swagger
            \nStatus of remote tunnel that is used to send alert emails.
        """
        self.__cluster_uuids = None
        self.__impact_types = None
        self.__include_global_email_contact_list = None
        self.__match_phrases = None
        self.__recipients = None
        self.__severities = None
        self.discriminator = None
        if cluster_uuids is not None:
            self.__cluster_uuids = cluster_uuids
        if impact_types is not None:
            self.__impact_types = impact_types
        if include_global_email_contact_list is not None:
            self.__include_global_email_contact_list = include_global_email_contact_list
        if match_phrases is not None:
            self.__match_phrases = match_phrases
        if recipients is not None:
            self.__recipients = recipients
        if severities is not None:
            self.__severities = severities
        # populate hidden vars if not empty
        self._populate_hidden_vars(kwargs)

    def _initialize_object_type(self):
        return 'prism.v4.config.EmailConfigurationRule'

    def _initialize_fq_object_type(self):
        return 'prism.v4.r0.a1.config.EmailConfigurationRule'

    def _populate_hidden_vars(self, kwargs):
        if "_reserved" in kwargs and kwargs["_reserved"] is not None:
            self.__dollar_reserved = kwargs["_reserved"]
        elif "_reserved" in self.attribute_map and self.attribute_map["_reserved"] in kwargs and kwargs[self.attribute_map["_reserved"]] is not None:
            self.__dollar_reserved = kwargs[self.attribute_map["_reserved"]]
        else :
            self.__dollar_reserved = {"$fqObjectType": self._initialize_fq_object_type()}
        if "_unknown_fields" in kwargs and kwargs["_unknown_fields"] is not None:
            self.__dollar_unknown_fields = kwargs["_unknown_fields"]
        elif "_unknown_fields" in self.attribute_map and self.attribute_map["_unknown_fields"] in kwargs and kwargs[self.attribute_map["_unknown_fields"]] is not None:
            self.__dollar_unknown_fields = kwargs[self.attribute_map["_unknown_fields"]]
        else :
            self.__dollar_unknown_fields = {}
        if "_object_type" in kwargs and kwargs["_object_type"] is not None:
            self.__dollar_object_type = kwargs["_object_type"]
        elif "_object_type" in self.attribute_map and self.attribute_map["_object_type"] in kwargs and kwargs[self.attribute_map["_object_type"]] is not None:
            self.__dollar_object_type = kwargs[self.attribute_map["_object_type"]]
        else:
            self.__dollar_object_type = self._initialize_object_type()

    def get_object_type(self):
        return self.__dollar_object_type

    def get_reserved(self):
        return self.__dollar_reserved

    def get_unknown_fields(self):
        return self.__dollar_unknown_fields

    @property
    def cluster_uuids(self):
        """`{ list[str] }`
            \nCluster UUIDs to which this rule applies to.
        """ # noqa: E501
        return self.__cluster_uuids

    @cluster_uuids.setter
    def cluster_uuids(self, cluster_uuids):

        self.__cluster_uuids = cluster_uuids

    @property
    def impact_types(self):
        """`{ list[prism.v4.common.ImpactType] }`
            
        """ # noqa: E501
        return self.__impact_types

    @impact_types.setter
    def impact_types(self, impact_types):

        self.__impact_types = impact_types

    @property
    def include_global_email_contact_list(self):
        """`{ bool }`
            
        """ # noqa: E501
        return self.__include_global_email_contact_list

    @include_global_email_contact_list.setter
    def include_global_email_contact_list(self, include_global_email_contact_list):

        self.__include_global_email_contact_list = include_global_email_contact_list

    @property
    def match_phrases(self):
        """`{ list[str] }`
            \nList of phrases to match the alert with.
        """ # noqa: E501
        return self.__match_phrases

    @match_phrases.setter
    def match_phrases(self, match_phrases):

        self.__match_phrases = match_phrases

    @property
    def recipients(self):
        """`{ list[str] }`
            \nList of recipients who will receive emails.
        """ # noqa: E501
        return self.__recipients

    @recipients.setter
    def recipients(self, recipients):

        self.__recipients = recipients

    @property
    def severities(self):
        """`{ list[prism.v4.common.Severity] }`
            
        """ # noqa: E501
        return self.__severities

    @severities.setter
    def severities(self, severities):

        self.__severities = severities

    @property
    def _reserved(self):
        """`{ dict(str, object) }`
            
        """ # noqa: E501
        return self.__dollar_reserved

    @property
    def _object_type(self):
        """`{ str }`
            
        """ # noqa: E501
        return self.__dollar_object_type

    @property
    def _unknown_fields(self):
        """`{ dict(str, object) }`
            
        """ # noqa: E501
        return self.__dollar_unknown_fields

    def _to_dict(self, sanitize):
        """
        Returns the model properties as a dict. Omits None properties based on the provided "sanitize" parameter.
        :param bool sanitize
        """

        result = {}

        for attr, attr_type in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x._to_dict(sanitize) if hasattr(x, "_to_dict") else x,
                    value
                ))
            elif hasattr(value, "_to_dict"):
                result[attr] = value._to_dict(sanitize)
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1]._to_dict(sanitize))
                    if hasattr(item[1], "_to_dict") else item,
                    six.iteritems(value)
                ))
            else:
                if sanitize:
                    if value is not None:
                        result[attr] = value
                else:
                    result[attr] = value
        if issubclass(EmailConfigurationRule, dict):
            for key, value in six.iteritems(self):
                result[key] = value

        return result

    def to_dict(self):
        """Returns the model properties as a dict"""
        return self._to_dict(False)

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self._to_dict(True))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmailConfigurationRule):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other

